UsersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: mood-users-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: pkey #userId
        AttributeType: S
      - AttributeName: skey #profile, device
        AttributeType: S
    KeySchema:
      - AttributeName: pkey
        KeyType: HASH
      - AttributeName: skey
        KeyType: RANGE
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
    Tags:
      - Key: Environment
        Value: ${self:provider.stage}

Outputs:
  UsersTableName:
    Value: !Ref UsersTable
  UsersTableArn:
    Value: !GetAtt UsersTable.Arn
  UsersTableStreamArn:
    Value: !GetAtt UsersTable.StreamArn
